// Public product data exported from admin_2.html.
window.CT_FEATURED_ID = 1;
window.CT_PRODUCTS = [
  {
    id: 1,
    name: 'Alienware Aurora R14',
    cat: 'gaming',
    status: 'active',
    price: 949,
    oldPrice: 1099,
    stock: 2,
    tag: 'HERNÝ ŠPECIÁL',
    tagColor: '#ef4444',
    cpu: 'AMD Ryzen 9 5900X',
    cpuBrand: 'amd',
    gpu: 'NVIDIA RTX 3080 10GB',
    gpuFilter: 'RTX 3080',
    ram: '32GB DDR4',
    ramFilter: '32',
    ssd: '1TB NVMe SSD',
    storageType: 'nvme',
    os: 'Windows 11 Pro',
    condition: 'Repasované – veľmi dobrý stav',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 98,
    newest: 20260708,
    description: 'Výkonný herný počítač pre 1440p gaming, streamovanie, tvorbu obsahu a náročné programy.'
  },
  {
    id: 2,
    name: 'HP Omen 40L',
    cat: 'gaming',
    status: 'active',
    price: 829,
    oldPrice: 949,
    stock: 5,
    tag: 'BESTSELLER',
    tagColor: '#2563eb',
    cpu: 'Intel Core i7-12700K',
    cpuBrand: 'intel',
    gpu: 'NVIDIA RTX 3070 Ti',
    gpuFilter: 'RTX 3070',
    ram: '16GB DDR4',
    ramFilter: '16',
    ssd: '512GB NVMe + 1TB HDD',
    storageType: 'nvme',
    os: 'Windows 11 Pro',
    condition: 'Repasované – veľmi dobrý stav',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 91,
    newest: 20260707,
    description: 'Silná herná zostava s výborným pomerom ceny a výkonu pre väčšinu moderných hier.'
  },
  {
    id: 3,
    name: 'Dell OptiPlex 7090 SFF',
    cat: 'office',
    status: 'active',
    price: 349,
    oldPrice: 429,
    stock: 8,
    tag: 'DO FIRMY',
    tagColor: '#16a34a',
    cpu: 'Intel Core i5-10500',
    cpuBrand: 'intel',
    gpu: 'Intel UHD Graphics',
    gpuFilter: 'UHD',
    ram: '16GB DDR4',
    ramFilter: '16',
    ssd: '256GB SSD',
    storageType: 'ssd',
    os: 'Windows 11 Pro',
    condition: 'Repasované – veľmi dobrý stav',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 87,
    newest: 20260706,
    description: 'Spoľahlivý pracovný počítač pre kanceláriu, školu, účtovníctvo a bežné domáce používanie.'
  },
  {
    id: 4,
    name: 'Lenovo ThinkCentre M720q Tiny',
    cat: 'office',
    status: 'active',
    price: 219,
    oldPrice: 279,
    stock: 6,
    tag: 'MINI PC',
    tagColor: '#0ea5e9',
    cpu: 'Intel Core i5-8500T',
    cpuBrand: 'intel',
    gpu: 'Intel UHD Graphics',
    gpuFilter: 'UHD',
    ram: '16GB DDR4',
    ramFilter: '16',
    ssd: '512GB SSD',
    storageType: 'ssd',
    os: 'Windows 11 Pro',
    condition: 'Repasované – dobrý stav',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 80,
    newest: 20260705,
    description: 'Malý a tichý počítač na stôl, za monitor alebo do školy. Výborný na bežnú prácu.'
  },
  {
    id: 5,
    name: 'Computrax Gaming Ryzen 5',
    cat: 'gaming',
    status: 'active',
    price: 599,
    oldPrice: 699,
    stock: 3,
    tag: 'CENA/VÝKON',
    tagColor: '#7c3aed',
    cpu: 'AMD Ryzen 5 5600',
    cpuBrand: 'amd',
    gpu: 'NVIDIA RTX 3060 12GB',
    gpuFilter: 'RTX 3060',
    ram: '16GB DDR4',
    ramFilter: '16',
    ssd: '1TB NVMe SSD',
    storageType: 'nvme',
    os: 'Windows 11 Pro',
    condition: 'Zložené z overených komponentov',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 89,
    newest: 20260708,
    description: 'Vyvážený herný PC pre Fortnite, CS2, GTA V, školu aj domácu tvorbu.'
  },
  {
    id: 6,
    name: 'Dell Precision Workstation',
    cat: 'office',
    status: 'active',
    price: 479,
    oldPrice: 569,
    stock: 2,
    tag: 'WORKSTATION',
    tagColor: '#f59e0b',
    cpu: 'Intel Xeon / Core i7 trieda',
    cpuBrand: 'intel',
    gpu: 'NVIDIA Quadro',
    gpuFilter: 'Quadro',
    ram: '32GB DDR4',
    ramFilter: '32',
    ssd: '512GB SSD',
    storageType: 'ssd',
    os: 'Windows 11 Pro',
    condition: 'Repasované – veľmi dobrý stav',
    warranty: '12 mesiacov',
    delivery: 'Kuriér / Packeta',
    image: '',
    tested: true,
    popular: 76,
    newest: 20260704,
    description: 'Pracovná stanica pre CAD, grafiku, účtovníctvo a náročnejšie firemné úlohy.'
  }
];
